### PR TITLE
added default array of disks value, for more convenient work

### PR DESCRIPTION
**Pull request by ezjust**
please approve my first pull-request

### CODE REVIEW

**Comment by MBugaiov** [comment]
First of all try do not change the structure of the script.
1) I think the help should not be highlighted for some options, when other are still not highlighted.
2) please use default option inside check_and_parse function. There should be check for the 'default option and array of the DISK should be passed in this case.
3) Do not use questions in the script. It is used in autotesting when user is not able to pass answers.

**Comment by ezjust** [comment]
please approve changes to configurator.sh ))

**Comment by ezjust** [comment]
removed check for null $DISK variable, for "default" array

**Comment by MBugaiov** [comment]
:+1:

**Pull request merged**
